[#3] Unit test configuration using catch2
collaborative-system/tea pull request #56
Opened 2024-10-22 21:05 UTC by Quik95

Using packaged `catch2` from a package manager, because manually setting it up using make is too much of a pain. If we ever decide to migrate to cmake, we can consider migrating it to building `catch2` from source.

2024-10-23 17:50 UTC, jagtym commented
> Using packaged `catch2` from a package manager, because manually setting it up using make is too much of a pain. 

Can you post here package version of catch2 package? I'll try to match it in flake.nix so we have exact same running in CI. 

> If we ever decide to migrate to cmake, we can consider migrating it to building `catch2` from source.

It there any reason for compiling it from source at the moment? Tests will mostly run in CI with pin-pointed version of the library.

Code looks good for me, approving!

2024-10-23 17:50 UTC, jagtym approved these changes

2024-10-23 21:25 UTC, mati2251 requested changes

2024-10-23 21:25 UTC, mati2251 commented on Makefile
> +.PHONY: test
For consistency, the test target should be named test-run and the test-binary target should be named test.

2024-10-25 16:04 UTC, mati2251 approved these changes

2024-10-25 16:13 UTC, mati2251 requested changes

2024-10-25 16:13 UTC, mati2251 commented on Makefile
> +.PHONY: test
@Quik95 .PHONY also needs to be changed. And `test-binary` should be `test`. I think that changes don't need new commit if before commits provide that stuff - similar too documentation commit. Personalny I would squash them to one new commit.

2024-10-26 11:05 UTC, mati2251 commented on Makefile
> +.PHONY: test
I improved this stuff because these features are crucial to the project and need to be merged quickly.

2024-10-26 11:05 UTC, mati2251 approved these changes

2024-10-26 11:06 UTC, merged